// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmyEKp4FYtPECz6YvzWqavYEdUT12Oh2A',
    appId: '1:927549859731:web:d833c87d29cacf5a56ea66',
    messagingSenderId: '927549859731',
    projectId: 'green-75f56',
    authDomain: 'green-75f56.firebaseapp.com',
    storageBucket: 'green-75f56.firebasestorage.app',
    measurementId: 'G-QR5YWPDT7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWcp1-2p68UH-buVvnmYddFy_maep-ZB4',
    appId: '1:927549859731:android:f9da10f6ff22537556ea66',
    messagingSenderId: '927549859731',
    projectId: 'green-75f56',
    storageBucket: 'green-75f56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWXTAWFe0OWGV9IottBHdg7hEdmCzHhUc',
    appId: '1:927549859731:ios:2d8e2110b4dcfdf056ea66',
    messagingSenderId: '927549859731',
    projectId: 'green-75f56',
    storageBucket: 'green-75f56.firebasestorage.app',
    iosClientId: '927549859731-b621n9o05pa0tauk15sogkrde1t5f574.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWXTAWFe0OWGV9IottBHdg7hEdmCzHhUc',
    appId: '1:927549859731:ios:2d8e2110b4dcfdf056ea66',
    messagingSenderId: '927549859731',
    projectId: 'green-75f56',
    storageBucket: 'green-75f56.firebasestorage.app',
    iosClientId: '927549859731-b621n9o05pa0tauk15sogkrde1t5f574.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmyEKp4FYtPECz6YvzWqavYEdUT12Oh2A',
    appId: '1:927549859731:web:d44a9a50ffe8741356ea66',
    messagingSenderId: '927549859731',
    projectId: 'green-75f56',
    authDomain: 'green-75f56.firebaseapp.com',
    storageBucket: 'green-75f56.firebasestorage.app',
    measurementId: 'G-N0N7WCK2TC',
  );
}
